### ISSUE TITLE
Homography files for UCY dataset

### ISSUE THREAD

**Issue by ajdroid** [erichhhhho/DataExtraction#1]
Hi, can you share the H.txt files you have for the UCY datasets (Zara/Univ). Do you remember how you calculated them?

**Comment by erichhhhho** [comment]
@ajdroid Hi, I have uploaded the [H.txt](https://github.com/erichhhhho/DataExtraction/blob/master/zara01/H.txt). I got it from the author of the paper _Who are you with and where are you going?_

**Comment by ajdroid** [comment]
Thanks! Are you using the same H for both Zara and Univ datasets?

**Comment by erichhhhho** [comment]
@ajdroid The Univ is using this [H.txt](https://github.com/erichhhhho/DataExtraction/blob/master/univ/H.txt).

**Comment by ajdroid** [comment]
Great, thank you!
