### ISSUE TITLE
H matrix for zara02

### ISSUE THREAD

**Issue by haowentang** [erichhhhho/DataExtraction#2]
Hi, can you tell me the H matrix for zara02? It can't be found in your files. Thanks a lot.

**Comment by haowentang** [comment]
@erichhhhho

**Comment by erichhhhho** [comment]
@haowentang zara01 and zara02 used the same H.txt

**Comment by erichhhhho** [comment]
To avoid confusion, I also uploaded it in the folder. Thanks

**Comment by haowentang** [comment]
OK， thank you very much！
